// 07-React18全家桶/08_ReactHooks/04_react-app-hooks/src/components/Counter.jsx
import {memo, useState} from "react"

function Counter() {
  const [count, setCount] = useState(0)
  
  const increment = () => {
    setCount(count + 1)
  }
  
  return (
    <div>
      <h3>当前计数为：{count}</h3>
      <button onClick={increment}>点我+1</button>
    </div>
  )
}

export default memo(Counter)

// 05-Vue3全家桶/06_额外补充/05_v-model解析/src/components/Counter.vue
<template>
  <h2>当前计数为：{{ modelValue }}</h2>
  <button @click="increment">点我+1</button>
</template>

<script>
export default {
  name: "Counter",
  props: ["modelValue"],
  emits: ["update:modelValue"],
  methods: {
    increment() {
      this.$emit("update:modelValue", this.modelValue + 1);
    }
  }
}
</script>


<style lang="less" scoped>

</style>
