// 07-React18全家桶/06_redux/04_react-app-redux/src/App.jsx
import React, {PureComponent} from 'react'
import Home from "@/components/Home"
import Banner from "@/components/Banner"
import Counter from "@/components/Counter"

class App extends PureComponent {
  
  state = {}
  
  render() {
    return (
      <div>
        <div style={{background: "pink", padding: '10px', width: '500px'}}>
          <Counter/>
        </div>
        <div style={{background: "skyblue", padding: '10px', width: '500px'}}>
          <Banner/>
        </div>
        <div style={{background: "orange", padding: '10px', width: '500px'}}>
          <Home/>
        </div>
      </div>
    )
  }
}

export default App

// 05-Vue3全家桶/05_Vue的状态管理/01_vue_vuex/src/App.vue
<template>
  <div class="app">
    <h2>App 组件，当前计数为：{{ count }}</h2>
    <Home/>
  </div>
</template>

<script setup>
import {computed} from "vue";
import {useStore} from "vuex";
import Home from "@/components/Home.vue";

const store = useStore()

const count = computed(() => {
  return store.state.count
})


</script>

<style lang="less">
.app {
  background-color: pink;
}
</style>
