// 05-Vue3全家桶/05_Vue的状态管理/02_vue_pinia/src/components/Counter.vue
<template>
  <h2>当前计数为：{{ counterStore.count }}</h2>
  <h2>2倍计数为：{{ counterStore.doubleCount }}</h2>
  <button @click="counterStore.increment()">点我+1</button>
</template>

<script setup>
import useCounterStore from "@/store/counter";

const counterStore = useCounterStore();

</script>

<style lang="less" scoped>

</style>

// 07-React18全家桶/08_ReactHooks/09_react-app-hooks/src/components/Counter.jsx
import React, {memo, useState} from 'react'
import {useDispatch, useSelector} from "react-redux"
import {decrement, increment} from "@/store/counter"

function Counter() {
  const [message] = useState("我是 Counter 组件")
  const count = useSelector(state => state.counter.count)
  const dispatch = useDispatch()
  
  
  console.log('Counter 渲染了')
  
  return (
    <div>
      <h2>{message}</h2>
      <h3>当前计数为：{count}</h3>
      <button onClick={() => dispatch(increment(1))}>点我+1</button>
      <button onClick={() => dispatch(decrement(1))}>点我-1</button>
    </div>
  )
}

export default memo(Counter)
