// 07-React18全家桶/05_React的CSS解决方案/03_react-app-css/src/components/Home.jsx
import React, {PureComponent} from 'react'
import HomeStyle from '@/components/Home.module.css'

class Home extends PureComponent {
  
  state = {
    message: '我是 Home 组件'
  }
  
  
  render() {
    const {message} = this.state
    return (
      <div className={"home"} style={{background: 'skyblue',padding:'5px'}}>
        <h2>{message}</h2>
        <div className={HomeStyle.title}>我是 Home 组件中的标题</div>
      </div>
    )
  }
}

export default Home

// 05-Vue3全家桶/04_组件通信/05_comp_comm-Provide&Inject/src/components/Home.vue
<template>
  <div class="home">
    Home
    <HomeBanner/>
  </div>
</template>

<script>
import HomeBanner from "@/components/HomeBanner.vue";

export default {
  name: "Home",
  components: {
    HomeBanner
  }
}
</script>


<style lang="less" scoped>
.home {
  padding: 50px;
  background-color: skyblue;
}
</style>
