// 07-React18全家桶/06_redux/04_react-app-redux/src/components/Home.jsx
import {PureComponent} from "react"
import {connect} from "@/hoc"
import {decrement, increment} from "@/store/counter"

class Home extends PureComponent {
  
  state = {
    message: '我是 Home 组件',
  }
  
  render() {
    const {message} = this.state
    console.log('Home', this.props)
    const {count, add, sub} = this.props
    return (
      <div>
        <h2>{message}</h2>
        <h3>当前计数为：{count}</h3>
        <button onClick={() => add(1)}>点我+1</button>
        <button onClick={() => sub(1)}>点我-1</button>
      </div>
    )
  }
}

const mapStateToProps = (state) => ({
  count: state.counter.count
})

const mapDispatchToProps = (dispatch) => ({
  add: (num) => dispatch(increment(num)),
  sub: (num) => dispatch(decrement(num))
})

export default connect(mapStateToProps, mapDispatchToProps)(Home)

// 05-Vue3全家桶/06_额外补充/03_keep-alive/src/components/Home.vue
<template>
  <h2>Home组件</h2>
  <h2>当前计数为：{{ count }}</h2>
  <button @click="count++">点我+1</button>
</template>

<script>
export default {
  name: "Home",
  data() {
    return {
      count: 0
    }
  },
  unmounted() {
    console.log("Home ... unmounted")
  }
}
</script>


<style lang="less" scoped>

</style>
