// 07-React18全家桶/08_ReactHooks/05_react-app-hooks/src/App.jsx
import {forwardRef, memo, useImperativeHandle, useRef, useState} from "react"


const Counter = memo(forwardRef((props, ref) => {
  const [message] = useState("我是 Counter 组件")
  const [count, setCount] = useState(0)
  
  const handleClick = () => {
    setCount(count + 1)
  }
  
  useImperativeHandle(ref, () => {
    return {
      handleClick: handleClick
    }
  }, [handleClick])
  
  return (
    <div ref={ref}>
      <h2>{message}</h2>
      <h2>当前计数为：{count}</h2>
      <button onClick={handleClick}>点击+1</button>
    </div>
  )
}))

function App() {
  const [message] = useState("我是 App 组件")
  const counterRef = useRef(null)
  
  
  const handleClick = () => {
    counterRef.current.handleClick()
  }
  
  return (
    <div>
      <div style={{background: 'pink', padding: '20px'}}>
        <h2>{message}</h2>
        <button onClick={handleClick}>点我+1</button>
        <div style={{background: 'skyblue', padding: '20px', marginTop: '20px'}}>
          <Counter ref={counterRef}/>
        </div>
      </div>
    </div>
  )
}

export default memo(App)

// 05-Vue3全家桶/07_Vue高级语法补充/vue-demo/src/App.vue
<template>
  <div class="app">
    <h2>我是h2元素</h2>
    <render></render>
    <divRender></divRender>
    <jsxRender></jsxRender>
    <counter></counter>
  </div>
</template>

<script lang="jsx" setup>
import {h, ref} from "vue"

// 第一种写法
function render() {
  return (h('div', {class: 'bar', innerHTML: 'hello', title: '我是div元素', style: {color: 'red'}}, []))
}

// 第二种写法
const divRender = () => (h('div', {class: 'bar', innerHTML: 'hello', title: '我是div元素', style: {color: 'red'}}, []))

function jsxRender() {
  return (
      <div style={{color: 'red'}} className="abc">我是div元素</div>
  )
}

const count = ref(0)

const add = () => {
  count.value++
}

function counter() {
  return (
      <div className="counter">
        <div>当前计数为：{count.value}</div>
        <button onClick={add}>点我+1</button>
      </div>
  )
}

</script>


<style scoped>
.abc {
  background-color: pink;
}

.counter {
  background-color: skyblue;
}
</style>
