// 05-Vue3全家桶/02_Vue的组件化开发/03_组件通信/06_comp_comm-事件总线/src/components/Home.vue
<template>
  <div class="home">
    Counter
    <HomeBanner/>
  </div>
</template>

<script>
import HomeBanner from "@/components/HomeBanner.vue";

export default {
  name: "Counter",
  components: {
    HomeBanner
  }
}
</script>


<style lang="less" scoped>
.home {
  padding: 50px;
  background-color: skyblue;
}
</style>

// 07-React18全家桶/05_React的CSS解决方案/02_react-app-css/src/components/Home.jsx
import React, {PureComponent} from 'react'
import '@/components/Home.css'

class Home extends PureComponent {
  
  state = {
    message: '我是 Home 组件'
  }
  
  
  render() {
    const {message} = this.state
    return (
      <div className={"home"} style={{background: 'skyblue',padding:'5px'}}>
        <h2>{message}</h2>
        <div className={"title"}>我是 Home 组件中的标题</div>
      </div>
    )
  }
}

export default Home
