// 05-Vue3全家桶/05_Vue的状态管理/01_vue_vuex/src/App.vue
<template>
  <div class="app">
    <h2>App 组件，当前计数为：{{ count }}</h2>
    <Home/>
  </div>
</template>

<script setup>
import {computed} from "vue";
import {useStore} from "vuex";
import Home from "@/components/Home.vue";

const store = useStore()

const count = computed(() => {
  return store.state.count
})


</script>

<style lang="less">
.app {
  background-color: pink;
}
</style>

// 07-React18全家桶/08_ReactHooks/01_react-app-hooks/src/App.jsx
import React, {PureComponent} from 'react'
import CounterClass from "@/components/CounterClass"
import CounterFunction from "@/components/CounterFunction"

class App extends PureComponent {
  
  state = {}
  
  render() {
    return (
      <div>
        <div style={{background: 'pink', padding: "20px"}}>
          <CounterClass/>
        </div>
        <div style={{background: 'skyblue', padding: "20px"}}>
          <CounterFunction/>
        </div>
      </div>
    )
  }
}

export default App
