// 07-React18全家桶/08_ReactHooks/04_react-app-hooks/src/components/Counter.jsx
import {memo, useState} from "react"

function Counter() {
  const [count, setCount] = useState(0)
  
  const increment = () => {
    setCount(count + 1)
  }
  
  return (
    <div>
      <h3>当前计数为：{count}</h3>
      <button onClick={increment}>点我+1</button>
    </div>
  )
}

export default memo(Counter)

// 05-Vue3全家桶/05_Vue的状态管理/02_vue_pinia/src/components/Counter.vue
<template>
  <h2>当前计数为：{{ counterStore.count }}</h2>
  <h2>2倍计数为：{{ counterStore.doubleCount }}</h2>
  <button @click="counterStore.increment()">点我+1</button>
</template>

<script setup>
import useCounterStore from "@/store/counter";

const counterStore = useCounterStore();

</script>

<style lang="less" scoped>

</style>
